export enum FunctionTypeEnum {
  SELECT_OPEN_ITEMS = 'SELECT_OPEN_ITEMS',
  MATCH_AMOUNT_ALL = 'MATCH_AMOUNT_ALL',
  MATCH_AMOUNT_SUBSETTING = 'MATCH_AMOUNT_SUBSETTING',
  MATCH_AMOUNT_SINGLE = 'MATCH_AMOUNT_SINGLE',
  MATCH_AMOUNT_VARIABLE = 'MATCH_AMOUNT_VARIABLE'
}